stages:

    profile:
        cmd: python3 src/profiling.py assets/data/raw/
        deps:
        - assets/data/raw
        - src/profiling.py
        - src/profile.yaml
        outs:
        - assets/profile
        params:
        - profile.dataset

    clean:
        cmd: python3 src/clean.py assets/data/raw/
        deps:
        - assets/data/raw
        - src/clean.py
        - assets/profile
        outs:
        - assets/data/cleaned
        - assets/data/output_columns.csv
        params:
        - clean.target
        - clean.classification
        - clean.onehot_encode_target
        - clean.combine_files
        - clean.percentage_zeros_threshold
        - clean.correlation_metric
        - clean.input_max_correlation_threshold

    featurize:
        cmd: python3 src/featurize.py assets/data/cleaned/
        deps:
        - assets/data/cleaned
        - assets/data/output_columns.csv
        - src/featurize.py
        outs:
        - assets/data/featurized
        - assets/data/input_columns.csv
        params:
        - featurize.features
        - featurize.add_rolling_features
        - featurize.remove_features
        - featurize.rolling_window_size
        - featurize.target_min_correlation_threshold
        - clean.target

    split:
        cmd: python3 src/split.py assets/data/featurized/
        deps:
        - assets/data/featurized
        - src/split.py
        outs:
        - assets/data/split
        params:
        - split.train_split
        - split.shuffle_files
        - split.calibrate_split

    scale:
        cmd: python3 src/scale.py assets/data/split/
        deps:
        - assets/data/split
        - assets/data/output_columns.csv
        - src/scale.py
        outs:
        - assets/data/scaled
        params:
        - clean.classification
        - scale.input
        - scale.output

    sequentialize:
        cmd: python3 src/sequentialize.py assets/data/scaled/
        deps:
        - assets/data/scaled
        - assets/data/output_columns.csv
        - src/sequentialize.py
        - src/preprocess_utils.py
        outs:
        - assets/data/sequentialized
        params:
        - clean.classification
        - sequentialize.hist_size
        - sequentialize.target_size
        - train.net

    combine:
        cmd: python3 src/combine.py assets/data/sequentialized/
        deps:
        - assets/data/sequentialized
        - src/combine.py
        outs:
        - assets/data/combined

    train:
        cmd: python3 src/train.py assets/data/combined/train.npz
        deps:
        - assets/data/combined
        - assets/data/output_columns.csv
        - src/train.py
        - src/model.py
        outs:
        - assets/models
        params:
        - clean.classification
        - train.net
        - train.n_epochs
        - train.batch_size
        - train.kernel_size
        - train.early_stopping
        - train.patience

    evaluate:
        cmd: python3 src/evaluate.py assets/models/model.h5 assets/data/combined/train.npz assets/data/combined/test.npz assets/data/combined/calibrate.npz
        deps:
        - assets/data/combined/test.npz
        - assets/data/output_columns.csv
        - assets/models/model.h5
        - src/evaluate.py
        params:
        - clean.classification
        metrics:
        - assets/metrics/metrics.json:
            cache: false
