stages:

    preprocess:
        cmd: python3 src/preprocess.py assets/data/raw
        deps:
        - assets/data/raw
        - src/preprocess.py
        outs:
        - assets/data/preprocessed
        params:
        - preprocess.dataset
        - preprocess.labels

    profile:
        cmd: python3 src/profiling.py assets/data/preprocessed
        deps:
        - assets/data/preprocessed
        - src/profiling.py
        - src/profile.yaml
        outs:
        - assets/profile

    clean:
        cmd: python3 src/clean.py assets/data/preprocessed
        deps:
        - assets/data/raw
        - src/clean.py
        - assets/profile
        outs:
        - assets/data/cleaned
        - assets/data/output_columns.csv
        params:
        - clean.target
        - clean.classification
        - clean.onehot_encode_target
        - clean.combine_files
        - clean.percentage_zeros_threshold
        - clean.correlation_metric
        - clean.input_max_correlation_threshold

    featurize:
        cmd: python3 src/featurize.py assets/data/cleaned/
        deps:
        - assets/data/cleaned
        - assets/data/output_columns.csv
        - src/featurize.py
        outs:
        - assets/data/featurized
        - assets/data/input_columns.csv
        params:
        - featurize.features
        - featurize.add_rolling_features
        - featurize.remove_features
        - featurize.rolling_window_size
        - featurize.target_min_correlation_threshold
        - clean.target

    train:
        cmd: python3 src/train.py assets/data/combined/train.npz
        deps:
        - assets/data/combined
        - assets/data/output_columns.csv
        - src/train.py
        - src/model.py
        outs:
        - assets/models
        params:
        - clean.classification
        - train.net
        - train.n_epochs
        - train.batch_size
        - train.kernel_size
        - train.early_stopping
        - train.patience

    evaluate:
        cmd: python3 src/evaluate.py assets/models/model.h5 assets/data/combined/train.npz assets/data/combined/test.npz assets/data/combined/calibrate.npz
        deps:
        - assets/data/combined/test.npz
        - assets/data/output_columns.csv
        - assets/models/model.h5
        - src/evaluate.py
        params:
        - clean.classification
        metrics:
        - assets/metrics/metrics.json:
            cache: false
