profile:
    dataset:

clean:
    target: label
    classification: True
    onehot_encode_target: False
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    features:
        # - chest_ecg
        - wrist_acc_x
        - wrist_acc_y
        - wrist_acc_z
        - wrist_temp
        # - wrist_eda
        - wrist_bvp
    add_rolling_features: True
    remove_features:
        - wrist_acc_x
        - wrist_acc_y
        - wrist_acc_z
        - wrist_temp
        # - wrist_eda
        - wrist_bvp
    rolling_window_size: 256
    target_min_correlation_threshold: 0.0

split:
    train_split: 0.7
    shuffle_files: False
    calibrate_split: 0.0

scale:
    input: standard
    output: minmax

sequentialize:
    window_size: 1
    target_size: 1
    shuffle_samples: False

train:
    learning_method: xgboost
    n_epochs: 500
    batch_size: 128
    kernel_size: 3
    early_stopping: True
    patience: 40

evaluate:
